### ISSUE TITLE
集成 Let's  Encrypt 来自动生成  IKEv2 / ocserv  用的证书 

### ISSUE THREAD

**Issue by ftao** [ftao/vpn-deploy-playbook#105]

**Comment by vmlinz** [comment]
Cool idea

**Comment by ftao** [comment]
ikev2 现在可用了。 
https://github.com/ftao/vpn-deploy-playbook/wiki/Setup-IKEv2-VPN-Server-with-SSL-Certs-from-Let's-Encrypt

**Comment by ftao** [comment]
open-connect 也可以了。 
https://github.com/ftao/vpn-deploy-playbook/wiki/Setup-OpenConnect-VPN-Server-with-SSL-Certs-from-Let's-Encrypt
