### ISSUE TITLE
自从 vpn all in One 之后，又不会用了。

### ISSUE THREAD

**Issue by shao222** [ftao/vpn-deploy-playbook#108]
更新了一次后，发觉所有 pptp l2tp 等都 all in one 了，但配置文件又不会写了。
可以指点一下吗？ 

只需要安装pptp和 l2tp的话，如何配置 host_vars/server.yml 文件，感谢。

**Comment by shao222** [comment]
自己慢慢摸索后，配置了 group_vars/vpn.yml  (只保留了 pptp 相关）
执行 ansible-playbook -i ansible_hosts.local vpn.yml

有个出错信息：
```
TASK: [ppp-radiusclient | Enforce radiusclient is installed] ****************** 
failed: [localhost] => {"failed": true}
msg: No package matching 'radiusclient1' is available
```
group_vars/vpn.yml  配置：

```
pptp_use_radius: false
pptp_dns_servers:
  - 8.8.4.4
  - 8.8.8.8
pptp_users:
  - username: "username"
    password: "password"
```

**Comment by ftao** [comment]
你的服务器操作系统版本是什么？

**Comment by shao222** [comment]
debian 8.0

**Comment by ftao** [comment]
这个新版本， 可能包名字改了..    目前比较完整的测试过的只有 ubuntu 14.04 , 部分在 debian 7.0 上测试过。 

你可以试试直接用   pptp.yml  /  ipsec.yml 来跑。 
https://github.com/ftao/vpn-deploy-playbook/wiki/%E9%85%8D%E7%BD%AEPPTP-VPN%E6%9C%8D%E5%8A%A1%E5%99%A8
https://github.com/ftao/vpn-deploy-playbook/wiki/Setup-L2TP-VPN-Server--(Using-Strongswan)

**Comment by shao222** [comment]
用 pptp.yml 可以跑起来。
