### ISSUE TITLE
Ipsec.yml on l2tp over ipsec 

### ISSUE THREAD

**Issue by shao222** [ftao/vpn-deploy-playbook#109]
openvz vps 

host_vars/localhost.yml
```
ipsec_enable_ikev1: false
ipsec_enable_ikev2: false
ipsec_enable_l2tp: true
ipsec_psk: vpnpsk
ipsec_use_radius: false
l2tp_users:
  - username: "username"
    password: "password"
```

执行
```
ansible-playbook ipsec.yml -l localhost
```
安装过程中也没有出错信息

xl2tpd 和 ipsec 都正常启动了。
但是l2tp 连接 就停在这里：
```
 charon: 08[NET] received packet: from [IP ADDRESS][500] to [VPS IP][500] (500 bytes)
 charon: 08[ENC] parsed ID_PROT request 0 [ SA V V V V V V V V V V V V ]
 charon: 08[IKE] received NAT-T (RFC 3947) vendor ID
 charon: 08[IKE] received draft-ietf-ipsec-nat-t-ike vendor ID
 charon: 08[IKE] received draft-ietf-ipsec-nat-t-ike-08 vendor ID
 charon: 08[IKE] received draft-ietf-ipsec-nat-t-ike-07 vendor ID
 charon: 08[IKE] received draft-ietf-ipsec-nat-t-ike-06 vendor ID
 charon: 08[IKE] received draft-ietf-ipsec-nat-t-ike-05 vendor ID
 charon: 08[IKE] received draft-ietf-ipsec-nat-t-ike-04 vendor ID
 charon: 08[IKE] received draft-ietf-ipsec-nat-t-ike-03 vendor ID
 charon: 08[IKE] received draft-ietf-ipsec-nat-t-ike-02 vendor ID
 charon: 08[IKE] received draft-ietf-ipsec-nat-t-ike-02\n vendor ID
 charon: 08[IKE] received FRAGMENTATION vendor ID
 charon: 08[IKE] received DPD vendor ID
 charon: 08[IKE] [IP ADDRESS] is initiating a Main Mode IKE_SA
 charon: 08[CFG] received proposals: IKE:AES_CBC_256/HMAC_SHA1_96/PRF_HMAC_SHA1/MODP_1024, IKE:AES_CBC_256/HMAC_MD5_96/PRF_HMAC_MD5/MODP_1024, IKE:AES_CBC_128/HMAC_SHA1_96/PRF_HMAC_SHA1/MODP_1024, IKE:AES_CBC_128/HMAC_MD5_96/PRF_HMAC_MD5/MODP_1024, IKE:3DES_CBC/HMAC_SHA1_96/PRF_HMAC_SHA1/MODP_1024, IKE:3DES_CBC/HMAC_MD5_96/PRF_HMAC_MD5/MODP_1024
 charon: 08[CFG] configured proposals: IKE:AES_CBC_256/HMAC_SHA1_96/PRF_HMAC_SHA1/MODP_2048
 charon: 08[IKE] no proposal found
 charon: 08[ENC] generating INFORMATIONAL_V1 request 3781735519 [ N(NO_PROP) ]
 charon: 08[NET] sending packet: from [VPS IP][500] to [IP ADDRESS][500] (56 bytes)
```

求助，这是哪里没处理好，还是说明这个 openvz 不支持 l2tp ipsec？

**Comment by ftao** [comment]
挺巧的。 我最近也有尝试在  openvz 上面跑,  似乎确实有问题。  
首先肯定要额外装一个  strongswan-plugin-kernel-libipsec  ，  其他的问题我也没有完全解决。 
你可以先尝试一下， 
```
apt-get install strongswan-plugin-kernel-libipsec
service strongswan restart 
service xl2tpd restart 
```

**Comment by ftao** [comment]
大部分的openvz 应该都是不支持   ipsec 的。  你的供应商如果没有特别说明支持 ipsec , 那很可能就是不支持的。

**Comment by shao222** [comment]
我针对 l2tp over ipsec  发过 tickets ，对方回复我：
```
I have enabled the required modules for you.
```
我在 SolusVM 面板里重启后，还是这样子。 我先去安装一下 libipsec 看看。

**Comment by shao222** [comment]
好像找不到这个安装包：
```
# apt-get install strongswan-plugin-kernel-libipsec
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package strongswan-plugin-kernel-libipsec
```

**Comment by ftao** [comment]
你是什么系统？ 

我测试的 ubuntu 14.04 确认有问题， 有bug ， 暂时无解。 除非自己去编译 strongswan .  
https://bugs.launchpad.net/ubuntu/+source/strongswan/+bug/1309594

**Comment by ftao** [comment]
还有一个选项可能有帮助
```
sysctl -w net.ipv4.conf.venet0.disable_policy=1
```

**Comment by shao222** [comment]
我是 debian  7.0

**Comment by ftao** [comment]
l2tp 放弃吧。 似乎是不行的。

下面这篇文章说明白了。 
https://ttz.im/2014/08/1184

    更新：在bug tracker里面询问了开发者，libipsec只支持tunnel模式，而iOS和Windows自带的L2TP/IPSec客户端都只支持transport，并且strongswan如果收到客户端请求使用transport模式的话会自动   转为transport，忽略掉设定里面的type=tunnel。

不过 ikev1  模式是可以的。 运行下面这句话就可以正常使用ikev1 模式了。  
```
sysctl -w net.ipv4.conf.venet0.disable_policy=1
```

**Comment by shao222** [comment]
好像确实如此，我编译好了 libstrongswan-kernel-libipsec.so
copy /usr/lib/ipsec/plugins/ 
restart ipsec / xl2tpd 也不行。

BTW，我已经用 strongswan 实现 ikev1 vpn了。唯独 l2tp 不行。

**Comment by shao222** [comment]
对了， 用 ipsec.yml 搭建 ikev1 ，在 openvz 还是有bug ，vpn 可以连接但无法访问网络。

**Comment by shao222** [comment]
好像 strongswan 必须下载源码，然后编译安装才可以。
我是参照这个：https://quericy.me/blog/512
以及： https://ttz.im/2015/10/1335

**Comment by ftao** [comment]
似乎是这个bug  
https://wiki.strongswan.org/issues/592

**Comment by ftao** [comment]
OK .  我确认确实需要重新编译加入  `libstrongswan-kernel-libipsec`  , 之后 ikev1 就可以了。

**Comment by shao222** [comment]
我正在重新 编译的路上。

**Comment by ftao** [comment]
这个Issue 的结论应该是 openvz  上需要重新编译加入  libstrongswan-kernel-libipsec   选项。 
unbuntu 上面的自动话的支持我做了一下， 但是 debian 上面不太一样，目前不支持。  
https://github.com/ftao/vpn-deploy-playbook/blob/master/roles/strongswan/tasks/openvz.yml

另外一个问题是  l2tp 在 openvz 上还是不支持的。

**Comment by ftao** [comment]
鉴于这个Issue 是关于 l2tp 的，目前的结论是openvz 无法支持 l2tp . 
先关闭这个issue 了。
