### ISSUE TITLE
在ubuntu 14.04.3 LTS x86_64安装ansible时报错

### ISSUE THREAD

**Issue by lopezycj** [ftao/vpn-deploy-playbook#126]
错误是
 src/MD2.c:31:20: fatal error: Python.h: No such file or directory
     #include "Python.h"
                        ^
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/pycrypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-_7Krqe-record/install-record.txt --single-version-externally-managed --compile:
    running install

**Comment by lopezycj** [comment]
然后我用apt-get install python-dev，安装ansible得到了一个警告
 Could not find .egg-info directory in install record for pycrypto>=2.6 (from ansible)
但提示安装成功了
但执行这个ansible-galaxy install --force -r requirements.yml

ERROR! Unexpected Exception: No module named markupsafe
the full traceback was:

Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 73, in <module>
    mycli = getattr(__import__("ansible.cli.%s" % sub, fromlist=[myclass]), myclass)
  File "/usr/local/lib/python2.7/dist-packages/ansible/cli/galaxy.py", line 31, in <module>
    from jinja2 import Environment
  File "/usr/local/lib/python2.7/dist-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 13, in <module>
    from jinja2 import nodes
  File "/usr/local/lib/python2.7/dist-packages/jinja2/nodes.py", line 19, in <module>
    from jinja2.utils import Markup
  File "/usr/local/lib/python2.7/dist-packages/jinja2/utils.py", line 531, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: No module named markupsafe

我用pip install markupsafe，但还是提示这个错误

**Comment by ftao** [comment]
安装ansible 本身的问题，请看ansible 的文档 http://docs.ansible.com/ansible/intro_installation.html#installation 
或者到ansible 社区寻求帮助。

**Comment by lopezycj** [comment]
执行这句pip install markupsafe，忘记再前面加个sudo，OK
