### ISSUE TITLE
关于APNP的配置（双IP地址问题）

### ISSUE THREAD

**Issue by simman** [ftao/vpn-deploy-playbook#20]
您好，可能又要向您请教问题了。

问题描述：

我已经配置好了所有的操作，并且已经可以正常访问  *.*.*.*:30080，但我发现代理地址的部分是错误的，因为我使用的国内主机是 阿里云，但它会提供两个IP，我想您的程序会自动获取 eth0 的ip进行配置，但恰巧，阿里云的机器的 eth0 网卡提供的ip是内网ip，而 eth1才是外网的IP地址，所以我替换了 `/var/www/pch/localhost` 这个目录下面 **所有** 文件的内网IP为外网IP，希望能使之工作。但我在如下环境下无法正常访问 **某些** 网站：

1、iphone 5 
2、os ：7.1
3、wifi 环境，并且设置里面的 http 代理 为自动，并且在里面分别输入了  *.*.*.*:30080 这里地址里面提供的两个文件。

期待您的回答，谢谢！

**Comment by simman** [comment]
请问 国内的 36128 端口没有起来，怎么处理？

**Comment by ftao** [comment]
36128 是 pac 文件的 web 服务。 是nginx 起来的。 
检查一下nginx 是否跑着。 
检查一下 nginx 的log  .  (/var/log/nginx/ 下面的文件， 看看是否有报错）

**Comment by simman** [comment]
```
2015/04/02 09:27:33| WARNING: Netmasks are deprecated. Please use CIDR masks instead.
2015/04/02 09:27:33| WARNING: IPv4 netmasks are particularly nasty when used to compare IPv6 to IPv4 ranges.
2015/04/02 09:27:33| WARNING: For now we will assume you meant to write /17
2015/04/02 09:27:33| WARNING: Netmasks are deprecated. Please use CIDR masks instead.
2015/04/02 09:27:33| WARNING: IPv4 netmasks are particularly nasty when used to compare IPv6 to IPv4 ranges.
2015/04/02 09:27:33| WARNING: For now we will assume you meant to write /22
2015/04/02 09:27:33| WARNING: Netmasks are deprecated. Please use CIDR masks instead.
2015/04/02 09:27:33| WARNING: IPv4 netmasks are particularly nasty when used to compare IPv6 to IPv4 ranges.
2015/04/02 09:27:33| WARNING: For now we will assume you meant to write /23
```

你好启动 squid3 的时候，出现这个，是什么原因？

**Comment by ftao** [comment]
是下面这个文件的问题， 是一个中国区域的IP 地址范围的配置文件格式的问题。 
https://github.com/ftao/vpn-deploy-playbook/blob/master/roles/squid/files/cn_ips.txt
新版本的squid 可能希望配置成 1.0.2.0/23 这种格式。 
但是这仅仅是一个warning 应该还是正常工作的。

**Comment by ftao** [comment]
close the issue due to inactive . 
free free to re-open  if  you still have problem .
