### ISSUE TITLE
openconnect.yml 装完后怎么用？

### ISSUE THREAD

**Issue by lexrus** [ftao/vpn-deploy-playbook#25]
是要去服务器上把证书下载下来再签一个客户端证书么？

**Comment by ftao** [comment]
这个报错的原因我也碰到， 是 非radius 方式， 然后也没有配置用户名， 导致 passwd 文件没有生成， 导致报错。  已经修正。

**Comment by SharkIng** [comment]
刚刚实验这个问题还有，请问是什么地方吃错了呢？

**Comment by ftao** [comment]
看了一下，之前代码似乎缺失没有修正 。
重新提交了一下， 现在应该修正了。 
https://github.com/ftao/vpn-deploy-playbook/commit/38be42b9e47b1191f6a23b1577462317f61f6de7
