### ISSUE TITLE
L2TP 部署之后无法使用

### ISSUE THREAD

**Issue by goldfish0506** [ftao/vpn-deploy-playbook#35]
按照 Setup L2TP VPN Server (Using Strongswan) 教程中进行设置的 
在 iOS 和 MAC 上都提示

> L2TP-VPN 服务器没有响应。请尝试重新连接。如果仍然有问题，请验证您的设置并与管理员联系。

我应该怎样判断L2TP 已经在服务器上 跑起来了?

**Comment by ftao** [comment]
确认 xl2tpd 和  strongswan 正常跑着
```
root@xxx:~# service strongswan status
strongswan start/running
root@xxx:~# ps aux | grep xl2tpd
root     13357  0.0  0.2  11748  2164 pts/10   S+   14:30   0:00 grep --color=auto xl2tpd
root     24477  0.0  0.2   5684  2848 ?        Ss   Jan01   1:47 /usr/sbin/xl2tpd
```
然后尝试连接的同时， tail xl2tpd 的日志
```
tail -f /var/log/xl2tpd.log
```

**Comment by goldfish0506** [comment]
前两步正常 
> tail -f /var/log/xl2tpd.log

之后尝试连接
没有任何反应

**Comment by ftao** [comment]
那说明网络不通啊。 请求根本没有到达服务器。
可能的原因：
1. 防火墙  －  可能是你的路由器， 也有可能是你的主机服务商的。 你是用的哪里的VPS/服务器？ 检查一下是否有防火墙问题。 
2. IP 被封了， 尝试换个IP 试试。

**Comment by goldfish0506** [comment]
好的 多谢~ 我用的 linode!  我再折腾一下吧~ 这个先 close了
