### ISSUE TITLE
集中在一处修改RADIUS服务器IP和Secret

### ISSUE THREAD

**Issue by frjalex** [ftao/vpn-deploy-playbook#37]
每次安装都需要到roles里面更改radius的secret和hostname，能不能集中一点提供更改呢？另外，能不能提供一个配置文件集中安装所有包含的yml文件，然后直接在一个地方修改默认配置就可以了呢？

Thanks.

**Comment by ftao** [comment]
具体你希望在一个服务器上跑哪些歌VPN 服务，需要你自己自己来定义的。 (写一个 vpn.yml playbook ) 
你需要定义一个组， 把变量都写在那边。(写一个  group_vars/vpn.yml)  
将你的服务器定义到 对应的组里面. (hosts)  

我提交了一个  vpn.yml ,  group_vars/vpn.yml.example  作为示范。

**Comment by frjalex** [comment]
谢谢，我先看看:)
