### ISSUE TITLE
有没有可能用 Ansible 自动编译一个支持 hybla 的内核模块？

### ISSUE THREAD

**Issue by lexrus** [ftao/vpn-deploy-playbook#39]
重度 VPN 用户会想要加上 hybla 支持吧。

**Comment by ftao** [comment]
没研究过。 理论上可以吧。
但是可能要到各个VPS 商上实际测试。

**Comment by lexrus** [comment]
自己编译的话大概步骤是这样： http://www.v2ex.com/t/114788
我在 Linode 的一台 Debian 上试了一下，人肉操作编译完差不多要 20 分钟。感觉要用脚本实现还是挻麻烦的，而且需求不是很迫切。
不过 Ubuntu 的内核默认就有 hybla 模块，可以考虑在优化 tcp 的时候 modprobe 加上 tcp_hybla。

**Comment by lexrus** [comment]
忽然觉得这个问题和 VPN 关系不大，算是网络优化的运维，先关掉了，谢谢。
