### ISSUE TITLE
Openvpn with radius issue

### ISSUE THREAD

**Issue by PhantomCoding** [ftao/vpn-deploy-playbook#43]
Whenever openvpn_use_radius are being set to true, it fails.
command used:

ansible-playbook -i ansible_hosts.local openvpn.yml -e openvpn_name=tcp_443 -e openvpn_port=443 -e openvpn_proto=tcp -e openvpn_use_radius=true --sudo

Error:
TASK: [openvpn-server | upload radiusplugin config file] **********************
fatal: [localhost] => {'msg': "One or more undefined variables: 'str object' has no attribute 'network'", 'failed': True}
fatal: [localhost] => {'msg': "One or more undefined variables: 'str object' has no attribute 'network'", 'failed': True}

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/openvpn.retry

localhost                  : ok=24   changed=13   unreachable=1    failed=0

EDIT: i should mention that i am using Ubuntu

**Comment by ftao** [comment]
That's a bug .   
Please update to latest code  and following the instruction at  [Setup OpenVPN Server](///ftao/vpn-deploy-playbook/wiki/Setup-OpenVPN-Server-With-Radius-Server)

**Comment by PhantomCoding** [comment]
It worked perfectly with a minor easly fixed issue on the way.

When trying to run it, i get the following:

TASK: [ftao.certified | add repo] *********************************************
failed: [testvm] => {"failed": true, "item": ""}
msg: Could not import python modules: pycurl. Please install python-pycurl package.

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/openvpn.retry

testvm                     : ok=8    changed=1    unreachable=0    failed=1


This was solved by doing an apt-get install python-pycurl


Thank you.
