### ISSUE TITLE
单机配置，ansible_ssh_host该怎么填写？

### ISSUE THREAD

**Issue by linsk** [ftao/vpn-deploy-playbook#45]
请问ansible_hosts中
ansible_ssh_host=192.168.1.14
其中 192.168.1.14 是指什么？单机的话应该如何填写？
谢谢

**Comment by ftao** [comment]
那个只是一个测试的虚拟机的IP。 
你如果是将这个项目在最终要跑的VPN 服务器的机器上面执行的， 请看 ansible_hosts.local 文件。 
`
sudo ansible-playbook -i ansible_hosts.local  vpn.yml 
`

**Comment by linsk** [comment]
感谢！ 如果把配置过程写成一个Shell就更好了，类似这种 https://github.com/aodzip/SPIKE/
