### ISSUE TITLE
有一句实在不懂怎么写，小白求教

### ISSUE THREAD

**Issue by allen0125** [ftao/vpn-deploy-playbook#52]
testvm.example.com ansible_ssh_host=192.168.1.14 ansible_ssh_user=vagrant  ansible_sudo=true

这句当中：testvm.example.com应该用我的VPS ip地址替换掉吧？

ansible_ssh_host应该填写什么呢？ ansible_ssh_user是不是应该为root？我的VPS要有ssh key验证这个该怎么办……

**Comment by ftao** [comment]
你这个情况， ansible_ssh_host 可以删除， 或者写成VPS IP 地址。 ansible_ssh_user  可以使root . 
对于  ssh key 验证的话，如果使用的私钥的位置就是默认的    $HOME/.ssh/id_rsa ， 那么什么都不用配置。  否则的话，请参考 ansible 的文档，要么手工配置密钥的位置， 要么使用 ssh-agent 。 
http://docs.ansible.com/intro_inventory.html#list-of-behavioral-inventory-parameters
http://linux.die.net/man/1/ssh-agent

**Comment by ftao** [comment]
建议你 读一下 ansible 的文档。  http://docs.ansible.com/intro_inventory.html

**Comment by allen0125** [comment]
好的，谢谢
