### ISSUE TITLE
有没有考虑把一些常用的roles拆出来，同时使用galaxy来管理

### ISSUE THREAD

**Issue by vmlinz** [ftao/vpn-deploy-playbook#56]
现在这个组合越来越大了，是否考虑吧roles拆出来，这里用galaxy来安装依赖？

可能这样做更好维护吧。

**Comment by ftao** [comment]
我现在有一些role会放在单独的仓库， 但是我不想依赖 galaxy 。  
要尽量做到开箱即用， 项目clone 下来就可以用了。
一些可以独立出去的role ，会放到独立的仓库， 然后在这个仓库通过 git subtree 的方式引入进来。 （比如 https://github.com/ftao/ansible-role-nginx-reverse-proxy  已经是这样了)

**Comment by vmlinz** [comment]
嗯，用subtree可以clone了就使用。当然roles拆出来了还是可以上传到galaxy，只是不一定适用galaxy来安装。这样其他人可以在这些role的基础上更好的去定制自己的组合。

这样也挺好的。我是看到https://github.com/ftao/ansible-role-nginx-reverse-proxy，这边用的subtree，我以为你考虑了galaxy了。

谢谢回复。

先close了：）
