### ISSUE TITLE
nghttp2 proxy来替换spdylay

### ISSUE THREAD

**Issue by vmlinz** [ftao/vpn-deploy-playbook#63]
参考https://wzyboy.im/post/1052.html

nghttp2 现在支持了最新的http2协议。

**Comment by ftao** [comment]
文中似乎说 chrome 还是有点问题的，还是只能用 spdy 的， 不过还是可以搞一下这种模式。  

> ：前文已经说明了，nghttp2 如其名字所示，是一个 HTTP/2 的库，但是由于 Chromium / Google Chrome 的一个 bug，截止 v45，Cr 对 HTTP/2 代理的支持有点问题

**Comment by vmlinz** [comment]
嗯，这样就只能在本地再起一个nghttpx把http转成http2发出去了。不过这个可以设置来直接以spdy3作为fallback，至少理论上应该可以替代现在的spdylay了。这个库本身链接了spdylay。

**Comment by vmlinz** [comment]
我先试试文章中的做法，如果可以的话我再把它集成到playbook中来

**Comment by ftao** [comment]
我准备要处理一下这个issue 。
@vmlinz  你有部分的成果我可以参考吗？

**Comment by vmlinz** [comment]
@ftao 我最近在忙其他的事情，暂时没有时间把nghttpx整理好。如果你先做出来，我可以帮忙测试。

**Comment by ftao** [comment]
@vmlinz  已经用 nghttp2 / spdylay 重新做了一个版本的  spdy proxy , 简单测试可用。 
https://github.com/ftao/vpn-deploy-playbook/wiki/Setup-SPDY-Proxy

**Comment by vmlinz** [comment]
@ftao, 非常感谢，我马上开始测试:)

**Comment by vmlinz** [comment]
测试使用大约一周时间，nghttpx运行稳定。我使用的配置是带客户端证书验证的，由于证书是自签名，chrome一直会提示确认使用该证书，在一定程度上影响了体验。

总体来说，nghttpx可以非常稳定的运行。

非常感谢你的实现:)

**Comment by ftao** [comment]
如果能写一下，如何让chrome 安装客户端证书， 就更好。

**Comment by vmlinz** [comment]
好的，我写一个guide。各个平台如何按照客户端证书。我在Mac上用起来很奇怪，每次连接都会提醒确认证书。可能是因为ca的问题，我用的自签的ca。

**Comment by lexrus** [comment]
@vmlinz 是不是用一般的 RapidSSL 或 ComodoSSL 可以解决证书的问题？

**Comment by vmlinz** [comment]
@lexrus 我还没有试过商业ssl证书，过几天我测试一下。

**Comment by ftao** [comment]
我这几天使用的  商业 ssl  ＋  squid 的 basic 认证 。 不会没有证书提示。 
上面说的证书提示应该是客户端证书吧， 这个的CA 不应该 也不需要 使用商用的证书。
