### ISSUE TITLE
关于PermitRootLogin no的问题

### ISSUE THREAD

**Issue by shao222** [ftao/vpn-deploy-playbook#68]
实用ansible 对vps 配置维护时候，如果vps设置了 PermitRootLogin no的话，是不是就无法正常操作了？
一般情况，我是禁止root ssh登录vps，我会用其他user ssh vps，然后再sudo。

请问这个情况，该如何操作？

**Comment by ftao** [comment]
这个配置 ansible_hosts 文件就可以了。
类似这样的写法。 
```
some-server ansible_ssh_host=192.168.33.10 ansible_ssh_user=vps_username 
```
然后执行ansible-playbook 的时候 加上 `--sudo` 选项， 如果需要输入sudo 密码的再加上 `-K`
```
ansible-playbook vpn.yml   --sudo  -K 
```
具体参数请看
```
ansible-playbook --help 
```

**Comment by shao222** [comment]
原来如此. 怪我没有仔细研究ansible. 谢谢!
