### ISSUE TITLE
还有个ipsec.yml的问题

### ISSUE THREAD

**Issue by shao222** [ftao/vpn-deploy-playbook#69]
我再host_vars/vps.yml 中，同时设置了 
ipsec_enable_ikev1: true
ipsec_enable_ikev2: true
ipsec_enable_l2tp: true

但最后发现, /etc/ipsec.secets 文件中,只有 ikev1和2的user/passwd, 却没有了l2tp user/passwd.

**Comment by ftao** [comment]
l2tp 的用户在  `/etc/ppp/chap-secrets`   
l2tp 的认证是交给 xl2tpd 处理的，不是 strongswan 处理的。

**Comment by scymen** [comment]
ftao 能否把使用说明写得更加详细一些？对于新手来说比较难懂，虽然是照着步骤来，但是还是有不少错误，花了不少的时间去寻找和搜索，最终还是没有解决，深受打击呀。

比如在README里的 HOT TO USE 
在pip install ansible 前，需要先安装一些依赖项（甚至有些机子可能连easy_install也没有）
apt-get update
apt-get install libpam0g-dev libssl-dev make gcc

接下来的第2、3步就让人迷惑了，修改并编辑ansible_hosts文件，如何修改，改成什么样儿，需要设置哪些参数？

第4步编辑group_vars里的ipsec.yaml.example ，我还是没能理解https://github.com/ftao/vpn-deploy-playbook/wiki/Setup-IKEv1-VPN-Server 跟ipsec.yaml.example里的设置，它们的参数testvm和vpn.example.com 是否是同一个？[ipsec]节点下的参数是什么？

不知道我没没有表达清楚。
谢谢

**Comment by ftao** [comment]
文档确实还不够完善。 
但这个很多都是  ansible 的知识，我下次把 ansible 基本文档的链接放上， ansible 相关的东西我自己写完全没有官方文档好用。

**Comment by ftao** [comment]
@shao222   问题解决了吗？ 这个Issue 可以close 吗？

**Comment by shao222** [comment]
@ftao 嗯 前面我看你们在说事情 所以我没close 

问题已经解决了。谢谢！
