### ISSUE TITLE
你好，关于ik1 认证有个地方要修改一下，不然验证不了

### ISSUE THREAD

**Issue by alroyso** [ftao/vpn-deploy-playbook#74]
rightauth2=xauth-eap  修改成这个   rightauth2=xauth-radius   不然无法通过eap-radius 来验证
strongswan  支持端口定义 我本地改了不知道怎么上传 希望作者改下哦。
关于ik2 证书跳过的问题，还有没有别的办法弄下呀？

**Comment by ftao** [comment]
ikev1 你确认吗？我的服务器是这么配置的， 可以正常使用啊。 
你碰到的错误信息是什么呢？ 

证书跳过问题，应该你的配置问题， 请把你的配置精简到最小最简单的能够重现问题的配法。再另外开issue 发上来。

**Comment by ftao** [comment]
> strongswan 支持端口定义 我本地改了不知道怎么上传 希望作者改下哦
这个看不懂。

**Comment by alroyso** [comment]
那可能是我这边的认证需要  rightauth2=xauth-radius 吧。

**Comment by ftao** [comment]
加了一个选项 ipsec_ikev1_radius_rightauth2  
如果你需要， 你可以设置下面的变量，就可以达到你的目的了。 
```
ipsec_ikev1_radius_rightauth2=xauth-radius
```
