### ISSUE TITLE
你好，我想使用172.0.0.1-172.255.255.253

### ISSUE THREAD

**Issue by alroyso** [ftao/vpn-deploy-playbook#76]
你好，我想使用172.0.0.1-172.255.255.253  这样大范围的IP 能不能做呀？

**Comment by ftao** [comment]
目前不支持。  至少可以说没有测试过，不知道是否支持。 
可以描述一下你的服务器的架构，以及为什么需要这样大的IP 地址段？ 
是真的需要这么大？ 还是其实使用的其中好几个IP 地址段和起来的？

**Comment by ftao** [comment]
结论是不支持。  close this issue now  .
