### ISSUE TITLE
Just found a new radius server implemented in python

### ISSUE THREAD

**Issue by vmlinz** [ftao/vpn-deploy-playbook#83]
A feature rich radius server implemented in python twisted.

https://github.com/talkincode/ToughRADIUS

Licensed under AGPL, I had a peek into this license, it gives users the rights to ask for source code of the software even if it is only used at the server side.

It provides 3 subsystems:

* Raidius AAA
* User/Admin
* Client side

It's management ui is way better than the existing radius management ui, and it integrates with the billing logics inside.

Br,
Nick

**Comment by ftao** [comment]
似乎挺有意思的。 有空跑一个 它的docker 起开研究一下。

**Comment by ftao** [comment]
see  roles/ftao.toughradius  ， 能用了， 但是目前版本 toughradius  似乎还是问题挺多。

**Comment by vmlinz** [comment]
@ftao, 非常感谢，我在环境里面试试看。

**Comment by ftao** [comment]
@vmlinz  toughradius 官方更新了几个版本了。  还是用他们推荐的 docker 方式吧。  
这个role 问题挺多的。

**Comment by vmlinz** [comment]
@ftao 嗯，在你另一个issue里面跟踪吧
