### ISSUE TITLE
内核静态tunnel 支持

### ISSUE THREAD

**Issue by ftao** [ftao/vpn-deploy-playbook#89]
实现一个这个 gist 描述的方法， 可以用来国内，国外服务器通讯。 

https://gist.github.com/klzgrad/5661b64596d003f61980

**Comment by vmlinz** [comment]
看起来不错啊

**Comment by ftao** [comment]
还是有 bug ,  re-open。 
存在 dns 问题， 要把DNS 服务器放到本地路由里去。 特别是当DNS 服务器是内网地址的时候。
