### ISSUE TITLE
测试一下rootpanel

### ISSUE THREAD

**Issue by vmlinz** [ftao/vpn-deploy-playbook#91]
#地址

https://github.com/jysperm/RootPanel

这个项目用nodejs和coffee实现了shadowsocks多端口的运营

#功能:

* 后台管理
* 多端口运行
* shadowsocks配置生成和管理
* shadowsocks进程管理
* 订单管理
* 付款
* 流量统计（iptables，思路和你做的tlg一样）
* 部署脚本
* 测试脚本

这个项目的代码质量比较高，维护也比较好。可以测试一下看看可不可以做一个playbook自动化部署

**Comment by ftao** [comment]
项目看起来好复杂。 没看明白。。

**Comment by vmlinz** [comment]
@ftao 我看着coffeescript的代码也麻烦，只有跑一下它的vagrant或者docker看看先。

**Comment by vmlinz** [comment]
closed as the project is no longer maintained
