### ISSUE TITLE
playbooks must be formatted as a YAML list, got <type 'dict'>

### ISSUE THREAD

**Issue by dbaflight** [ftao/vpn-deploy-playbook#96]
![la](https://cloud.githubusercontent.com/assets/10863552/9292185/365bc64c-441c-11e5-841f-20c994030f2f.jpg)

这是group_vars/ipsec.ymlipsec.yml截图。
ansible也是按照 准备控制机 安装的。
执行 ansible-playbook ipsec.yml -l testvm 后提示ERROR: parse error: playbooks must be formatted as a YAML list, got <type 'dict'>

**Comment by ftao** [comment]
这边没法重现这个问题啊。 
ipsec.yml 这个文件时最新版本吗？ 
执行一下  git pull ， 更新这个仓库的最新版本， 
贴一下你的    ipsec.yml 文件， 以及 ansible_hosts  （把个人信息／ip地址什么的遮掉）

**Comment by dbaflight** [comment]
ansible_hosts
![hosts](https://cloud.githubusercontent.com/assets/10863552/9292402/619f2814-4429-11e5-80dd-7be83e5087ae.jpg)

**Comment by dbaflight** [comment]
![hosts](https://cloud.githubusercontent.com/assets/10863552/9292421/830e85b6-442a-11e5-882e-87c1440db209.jpg)

**Comment by dbaflight** [comment]
ipsec.yml应该是最新，前几天才安装的

**Comment by dbaflight** [comment]
一楼就是我的ipsec.yml

**Comment by ftao** [comment]
你应该执行的 group_vars/ipsec.yml  ,  应该执行应该是上一层的  ipsec.yml ,    groups_vars/ipsec.yml 只是配置文件。

**Comment by dbaflight** [comment]
谢谢，这个问题已经解决.

**Comment by dbaflight** [comment]
另一个问题是，我在按照https://github.com/ftao/vpn-deploy-playbook/wiki/%E9%85%8D%E7%BD%AEL2TP-VPN%E6%9C%8D%E5%8A%A1%E5%99%A8-(Using-OpenSwan)这个方法配置时，vpn密钥是在什么地方配置的？谢谢！

**Comment by dbaflight** [comment]
才开始接触github和ansible，问题有点多啊希望亲能够抽出宝贵的时间解答一下 感激不尽啦 :)

**Comment by dbaflight** [comment]
我搭建好了pptp，可以使用，但连l2tp时就提示服务器无响应了。

**Comment by ftao** [comment]
VPN 密钥是这个配置项目。 
```
ipsec_psk: ipsecworks
```

**Comment by ftao** [comment]
服务器无响应的话， 你可以去服务器重启一下  xl2tpd  和 strongswan  , 然后看看日志有没有什么错误。

**Comment by dbaflight** [comment]
谢谢

**Comment by dbaflight** [comment]
经过重启xl2tpd 和 strongswan，日志没什么问题，还是不行。是否有其他原因可能导致？谢谢

**Comment by ftao** [comment]
坚持共享密钥是否对？ 
还不多，那就只能是网络问题了。

**Comment by dbaflight** [comment]
谢谢。
