### ISSUE TITLE
ikev2 是否有新增用户接口？

### ISSUE THREAD

**Issue by geekan** [ftao/vpn-deploy-playbook#97]
之前定义了十来个，但看起来不大够用了。
重新跑一遍流程是否可行？
我记得中间有一些过程会修改密钥/证书，是否有所影响？

**Comment by ftao** [comment]
重新跑一边就可以了。 
证书如果已经存在， 不会重新生成的。

**Comment by geekan** [comment]
好，多谢，我试试

**Comment by ftao** [comment]
应该不会有问题。 添加用户重新跑一遍时完全可以的。 
close it now
