### ISSUE TITLE
IKEv2是否支持windows？

### ISSUE THREAD

**Issue by geekan** [ftao/vpn-deploy-playbook#98]
https://github.com/ftao/vpn-deploy-playbook/wiki/Setup-IKEv2-VPN-Server
试了几个strongswan的连接方法，但都没法连接上VPN

**Comment by ftao** [comment]
我使用配置如下，是可以工作的。 
1.  商业证书   （所有不需要导入证书） 
2.  使用 windows 7 以上自带的 IKev2 支持， 没有使用 strongswan 客户端。 

理论上， 使用自己的CA 签署的证书的话只要把 CA 证书／服务器证书导入到系统之后也是可以连接的。 
我记得配置成功过的。 

没有试过strongswan 客户端。

**Comment by geekan** [comment]
好，我猜可能是VPS的问题，我换一台试试。

**Comment by ftao** [comment]
IKEv2 现在推荐使用 Let's Encrypt 来生成证书， 自己签名太麻烦。 
https://github.com/ftao/vpn-deploy-playbook/wiki/Setup-IKEv2-VPN-Server-with-SSL-Certs-from-Let's-Encrypt
欢迎测试一下， 如果没有问题， 可以把这个issue 关掉了。

**Comment by ftao** [comment]
我测试过。 使用系统认识的证书 Windows 下面 IKEv2 完全没有问题。 
先关闭了。   有问题，可以再提出。
